### PR TITLE
added destructors

### PR DESCRIPTION
**Pull request by emekoi**
fixed memory leak for `BN` type. now the following:
```nim
import BN

proc main() =
  while true:
    discard newBN()

main()
```
doesn't leak any memory.

### CODE REVIEW

**Comment by kayabaNerve** [comment]
```
Error: execution of an external program failed: 'build/'
```

What OS/Nim compiler/C compiler are you using?

**Comment by emekoi** [comment]
i am on windows using nim 0.18.0 with mingw-w64-i686-gcc 7.3.0-2. what are are running build on? Ember or BN?

**Comment by kayabaNerve** [comment]
I'm building the sample code as Ember's src\main.nim. I'm on Nim DEVEL using TDM-GCC 5.1 and getting `Critical error detected c0000374` (stack corruption).

**Comment by emekoi** [comment]
using devel with the leak example works without a problem, so i'll see if i can reproduce your error.

**Comment by kayabaNerve** [comment]
With BN's master branch or your BN fork?

**Comment by emekoi** [comment]
with my fork.

**Comment by emekoi** [comment]
with my fork i get an failed assert but with the master branch i get a segfault.

**Comment by kayabaNerve** [comment]
I just recompiled devel.

Memory leak on master, both on C and C++.

"Error: execution of an external program failed" on your fork, both on C and C++.

I would move to Linux but I'm pretty sure IMath in general is broken on Linux :/ Testing now...

**Comment by kayabaNerve** [comment]
Lubuntu, GCC 7.2, Nim devel (just recompiled).
```
*** Error in `./build/Ember': double free or corruption (out): 0x00007f86d371b050 ***
```

**Comment by emekoi** [comment]
okay, i cloned Ember. then i built it using `nim cpp src/main.nim` and my fork of BN. when i run it i get `true` is stdout.

**Comment by kayabaNerve** [comment]
Rewrite main.nim to be the memory leak sample code.

**Comment by emekoi** [comment]
this is what main looks like now:
```nim
import BN

proc main() =
  while true:
    discard newBN()

main()
```
and i still don't get a leak.

**Comment by kayabaNerve** [comment]
So then the question is why my Windows and Lubuntu setups can't...

**Comment by kayabaNerve** [comment]
Or rather, why your system can. We're 1/3 here, and I rather assume that 1 is the oddity than the 2...

**Comment by emekoi** [comment]
i'm going to try it on a macbook next.

**Comment by emekoi** [comment]
i see the problem now. you are supposed to use `mp_int_free` on `mpz_t` structs you obtain with `mp_int_alloc`. when you have a normal `mpz_t` and you initialize it using it's address you would destroy it using `mp_int_clear`.

**Comment by kayabaNerve** [comment]
Damn! Great job. Thanks. I'm going to increase the bounty from $25 to $50 for how long this took.

I'm also going to close this PR and make a commit (which you'll be cited in) with the destructor, because while I liked, and kept, some of your big changes (C in one group, Nim in the other; mp_result), the spaces man (and lack of comments on the Nim funcs, and unsafeAddr)... I also don't like a messy commit history and don't have a Git CLI to run `squash` from.

That said, truly thank you.

**Comment by emekoi** [comment]
sorry about the commit history ;)

**Pull request closed without merging**
